name: Allure Report and Publish to GitHub Pages

on:
  push:
    branches:
      - main  # или ваша рабочая ветка
  pull_request:
    branches:
      - main

jobs:
  upload_and_publish_report:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Проверка наличия результатов Allure
      - name: Check Allure Results Exist
        run: |
          if [ ! -d "./allure_results" ]; then
            echo "Allure results not found!"
            exit 1
          fi

      # Шаг 3: Установка Allure
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure-2.18.1.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      # Шаг 4: Генерация однофайлового отчета (index.html)
      - name: Convert Allure Report to Single HTML
        run: |
          allure generate -c --single-file ./allure_results -o ./allure-report-html

      # Шаг 5: Подготовка уникального пути для отчета
      - name: Prepare Unique Folder Name
        run: |
          REPORT_FOLDER="report-$(date +'%Y-%m-%d_%H-%M-%S')"
          echo "REPORT_FOLDER=$REPORT_FOLDER" >> $GITHUB_ENV

      # Шаг 6: Клонирование ветки gh-pages
      - name: Clone gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages

      # Шаг 7: Копирование нового отчета в уникальную папку
      - name: Copy Report to Unique Folder
        run: |
          mkdir -p gh-pages/$REPORT_FOLDER
          cp -r ./allure-report-html/* gh-pages/$REPORT_FOLDER

      # Шаг 8: Обновление корневого index.html для списка отчетов
      - name: Update Index File
        run: |
          echo "<html><body><h1>Allure Reports</h1><ul>" > gh-pages/index.html
          for dir in $(ls gh-pages); do
            if [ -d "gh-pages/$dir" ]; then
              echo "<li><a href=\"$dir/index.html\">$dir</a></li>" >> gh-pages/index.html
            fi
          done
          echo "</ul></body></html>" >> gh-pages/index.html

      # Шаг 9: Публикация отчета на GitHub Pages
      - name: Deploy Allure Reports to GitHub Pages
        run: |
          cd gh-pages
          git add .
          git commit -m "Add new Allure report ($REPORT_FOLDER)"
          git push origin gh-pages
