name: Allure Report and Publish to GitHub Pages

on:
  push:
    branches:
      - main  # или ваша рабочая ветка
  pull_request:
    branches:
      - main

jobs:
  upload_and_publish_report:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Allure (если необходимо)
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure-2.18.1.tgz
          sudo mv allure-2.18.1 /opt/allure
          export PATH=$PATH:/opt/allure/bin

      # Шаг 3: Генерация отчета Allure (если не был сгенерирован заранее)
      - name: Generate Allure Report
        run: |
          allure generate ./path/to/allure-results --clean -o ./allure-report

      # Шаг 4: Загрузка отчета Allure как артефакт
      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report

      # Шаг 5: Публикация отчета на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report  # Папка с готовым отчетом
