name: Allure Report and Publish to GitHub Pages

on:
  push:
    branches:
      - main  # или ваша рабочая ветка
  pull_request:
    branches:
      - main

jobs:
  upload_and_publish_report:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Проверка наличия результатов Allure
      - name: Check Allure Results Exist
        run: |
          if [ ! -d "./allure_results" ]; then
            echo "Allure results not found!"
            exit 1
          fi

      # Шаг 3: Установка Allure
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure-2.18.1.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      # Шаг 4: Генерация однофайлового отчета (index.html)
      - name: Convert Allure Report to Single HTML
        run: |
          allure generate -c --single-file ./allure_results -o ./allure-report-html

      # Шаг 5: Создание директории для отчета
      - name: Prepare Report Directory
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          REPORT_DIR="reports/$TIMESTAMP"
          mkdir -p "./allure-reports/$REPORT_DIR"
          mv ./allure-report-html/* "./allure-reports/$REPORT_DIR/"
          echo $REPORT_DIR > report_dir.txt

      # Шаг 6: Загрузка новых и старых отчетов
      - name: Upload Old and New Reports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          mkdir -p reports
          cp -r ./allure-reports/reports/* reports/
          git add reports
          git commit -m "Add Allure report $TIMESTAMP"
          git push origin gh-pages

      # Шаг 7: Обновление индекса
      - name: Update Index
        run: |
          INDEX_FILE="index.html"
          echo "<html><head><title>Allure Reports</title></head><body><h1>Allure Reports</h1><ul>" > $INDEX_FILE
          for REPORT in $(ls reports); do
            echo "<li><a href=\"reports/$REPORT/index.html\">Report $REPORT</a></li>" >> $INDEX_FILE
          done
          echo "</ul></body></html>" >> $INDEX_FILE
          cp $INDEX_FILE ./allure-reports/
          git add $INDEX_FILE
          git commit -m "Update report index"
          git push origin gh-pages