name: Allure Report and Publish to GitHub Pages

on:
  push:
    branches:
      - main  # или ваша рабочая ветка
  pull_request:
    branches:
      - main

jobs:
  upload_and_publish_report:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Проверка наличия результатов Allure
      - name: Check Allure Results Exist
        run: |
          if [ ! -d "./allure_results" ]; then
            echo "Allure results not found!"
            exit 1
          fi

      # Шаг 3: Установка Allure
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure-2.18.1.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
      

      # Шаг 4: Генерация однофайлового отчета (index.html)
      - name: Convert Allure Report to Single HTML
        run: |
         allure generate -c --single-file ./allure_results -o ./allure-report-html


      # Шаг 5:  Загрузка однофайлового отчета как артефакт
      - name:  Upload Single HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-html
          path: ./allure-report-html

      # Шаг 6: Публикация отчета на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report-html
          publish_branch: gh-pages



