name: Allure Report and Publish to GitHub Pages

on:
  push:
    branches:
      - main  # или ваша рабочая ветка
  pull_request:
    branches:
      - main

jobs:
  upload_and_publish_report:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2


      # Шаг 4: Загрузка отчета Allure как артефакт
      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure_results
          path: ./allure_results

      # Шаг 5: Публикация отчета на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure_results  # Папка с готовым отчетом

