name: Allure Report and Publish to GitHub Pages

on:
  push:
    branches:
      - main  # или ваша рабочая ветка
  pull_request:
    branches:
      - main

jobs:
  upload_and_publish_report:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Проверка наличия результатов Allure
      - name: Check Allure Results Exist
        run: |
          if [ ! -d "./allure_results" ]; then
            echo "Allure results not found!"
            exit 1
          fi

      # Шаг 3: Установка Allure
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure-2.18.1.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      # Шаг 4: Генерация однофайлового отчета (index.html)
      - name: Convert Allure Report to Single HTML
        run: |
         allure generate -c --single-file ./allure_results -o ./allure-report-html

      # Шаг 5: Получение уникального имени для нового отчета (например, с использованием времени)
      - name: Set unique report name
        id: report_name
        run: |
          echo "report_name=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      # Шаг 6: Создание ветки gh-pages, если она не существует
      - name: Create gh-pages branch if not exists
        run: |
          git fetch origin
          git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages

      # Шаг 7: Публикация отчета на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report-html
          publish_branch: gh-pages
          commit_message: "Deploy Allure report: ${{ env.report_name }}"

      # Шаг 8: Перемещение старых отчетов в папки с уникальными именами
      - name: Move old reports to unique folders
        run: |
          # Создаём папку с уникальным именем для отчета
          mkdir -p ./gh-pages/${{ env.report_name }}
          mv ./allure-report-html/* ./gh-pages/${{ env.report_name }}

      # Шаг 9: Публикация обновленной ветки gh-pages
      - name: Commit and push updated gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Update allure reports with new version"
          git push origin gh-pages
